### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by prolajumokeoni**
# Milestone 2: tnw-clone

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
🎉Hello, my good friends, Your project looks almost the same as the original, keep up the good works. There are few issues to fix before we move.
**required** you have left out one portion of the project check attached screenshots.
categories
**Required** the gaps in the latest deals and the latest news are too big, see here 
latest
**Required** The latest deals/latest news should have 4 parts or articles see here
desk
Please fix all this and submit another review request, **Note:** you only have two more reviews remaining.
In case you have a question, please find me on slack Elisha kyakopo
Cheers!👈💪✔🎉

**Comment by prolajumokeoni** [comment]
> 🎉Hello, my good friends, Your project looks almost the same as the original, keep up the good works. There are few issues to fix before we move.
> **required** you have left out one portion of the project check attached screenshots.
> categories
> **Required** the gaps in the latest deals and the latest news are too big, see here
> latest
> **Required** The latest deals/latest news should have 4 parts or articles see here
> desk
> Please fix all this and submit another review request, **Note:** you only have two more reviews remaining.
> In case you have a question, please find me on slack Elisha kyakopo
> Cheers!👈💪✔🎉

Thank you for your review elisha2kyakpo1, we have reduced the gaps, and submitted for another review, but we can't see the portion we missing at the categories section. 

 @elisha2kyakpo1

**Comment by elisha2kyakpo1** [comment]
Hello @prolajumokeoni, I meant all categories section is missing in your project. If I'm wrong send a zoom link so that you show me

**Comment by prolajumokeoni** [comment]
> Hello @prolajumokeoni, I meant all categories section is missing in your project. If I'm wrong send a zoom link so that you show me

[live demo](https://prolajumokeoni.github.io/tnw-clone/) 
The categories section is in our page is directly below the latest funding section and above the latest deals section. 

### If it is still not showing then I can send a zoom meeting like on slack, thank you! 


@elisha2kyakpo1

**Comment by elisha2kyakpo1** [comment]
Give each section a heading, like categories, etc. This may affect even the second reviewer, I have checked your project several times, but I can't see that part, I expect it to be below the three big articles on top. Follow the instructions on how to arrange sections, do not follow the original arrangement "The 3 sections are not in the order that they have on the website, but in the order, we recommend you to implement them.".

**Comment by prolajumokeoni** [comment]
> Give each section a heading, like categories, etc. This may affect even the second reviewer, I have checked your project several times, but I can't see that part, I expect it to be below the three big articles on top. Follow the instructions on how to arrange sections, do not follow the original arrangement "The 3 sections are not in the order that they have on the website, but in the order, we recommend you to implement them.".

We will work on that, thank you!

**Comment by prolajumokeoni** [comment]
> Give each section a heading, like categories, etc. This may affect even the second reviewer, I have checked your project several times, but I can't see that part, I expect it to be below the three big articles on top. Follow the instructions on how to arrange sections, do not follow the original arrangement "The 3 sections are not in the order that they have on the website, but in the order, we recommend you to implement them.".

@elisha2kyakpo1  we have added some comments to where the three sections start also a class with the name "categories section" to category section, thank you for the explanation.

**Review by Elbie-em — APPROVED** [review]
## STATUS: APPROVED :white_check_mark:

Hello @prolajumokeoni and @emmyobonyo, I would like to congratulate you on applying the requested changes and I am therefore approving this project. However there some changes I suggest you should apply to your project to make it look more professional for your portfolio before you move on.

## [OPTIONAL]

- [ ] Kindly consider altering the fonts and spacing(padding and margins) so that they correspond with the TNW website. You can use this [link](https://perma.cc/M5ZV-Q2D6) as a reference.
    > You can use chromes inspection tool to guide you on what figures to use with padding and margins.

- [ ] Kindly remove comments in your index.html and CSS files.

### :tada:   All the best with your next project.

**Comment by prolajumokeoni** [comment]
> ## STATUS: APPROVED ✅
> Hello @prolajumokeoni and @emmyobonyo, I would like to congratulate you on applying the requested changes and I am therefore approving this project. However there some changes I suggest you should apply to your project to make it look more professional for your portfolio before you move on.
> 
> ## [OPTIONAL]
> * [ ]  Kindly consider altering the fonts and spacing(padding and margins) so that they correspond with the TNW website. You can use this [link](https://perma.cc/M5ZV-Q2D6) as a reference.
>   > You can use chromes inspection tool to guide you on what figures to use with padding and margins.
> * [ ]  Kindly remove comments in your index.html and CSS files.
> 
> ### 🎉 All the best with your next project.

Thank you for your review @Elbie-em, we will work on the optional changes.

**Pull request closed without merging**
