### PR TITLE
Desktop

### PR DESCRIPTION
**Pull request by prolajumokeoni**
### Tnw-clone
> In this project:
- We started with the mobile-first approach
- We used media queries for the medium and desktop on different branches
- we applied flex to the header and footer
- We used grid to display the images in the highlights section
##### We have implemented all changes requested by the previous reviewer.

### CODE REVIEW

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
# Status: ♻️ Changes Required ♻️
## Hi @prolajumokeoni  and @emmyobonyo, I'm Dipesh your reviewer for this PR 👩‍🚀 
This setup looks nice and clean.
Also, I have to appreciate that your website looks very much similar to the original one and you have done a very good job so far. But in order to approve we have to work on some of the changes mentioned below.

I am dividing these changes according to section and screen sizes. so, that you will clear where to do changes

## Header

**Tablet**

- [x] The logo is on the leftmost part. For now, I can't able to see the logo on the leftmost part.

## HIghlights (top 3 articles)

**All screen sizes**

- [x] It contains 3 articles with an image as a background. For now, I am seeing you are not using the background image. Please change those images as a background.
- [x] The title of each article is a header (hx tag) and has a link (a tag). For now, I am seeing only the header tag and no link (a tag).

**Desktop**

- [x] The TWN logo should appear over the first article, at the top left corner. For now, it's showing nothing
- [x] The date should appear over the first article, at the top right corner.

## Latest Funding section

**All screen sizes**

- [x] The title of the section is a header (hx tag) and has a link (a tag). For now, I am seeing only the header tag and no link (a tag).
- [x] The nav menu (See more, Get updates, etc.) are grouped in a nav tag, and each one has link (a tag). For now, It is grouped in a `div` tag and did not use the anchor(a) tag.
- [x] Each article should have
           - Its own title (hx tag) and has a link (a tag)
           - Two categories items, with a link (a tag)
           - A text excerpt at the bottom, that also has a link (a tag)

- [x] The gap between image and text is unresponsive. sometimes they overlap. Please fix that.

**Desktop**

- [x] The nav menu should be on the left of the main title. For now, It is below the main title.
- [x] The first 4 articles appear in a row. For now, It's only 3.

## Footer

- [x] Footer contains social media icons that should be grouped in the `nav` tag and each of them with a link (a tag).
- [x] Below the social media menu, there should be another menu also centered, with a `nav` tag. For now, it is wrapped in a div tag.
---------

## Reminder

**"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have 2 code reviews left for this project."**

Code review by **Dipesh Kumar**

(Feel free to contact me on slack by the handle of  **deep** if you have any additional question).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk)
[Twitter](https://twitter.com/97deepeshkumar)

**Comment by prolajumokeoni** [comment]
> # Status: ♻️ Changes Required ♻️
> ## Hi @prolajumokeoni and @emmyobonyo, I'm Dipesh your reviewer for this PR 👩‍🚀
> This setup looks nice and clean.
> Also, I have to appreciate that your website looks very much similar to the original one and you have done a very good job so far. But in order to approve we have to work on some of the changes mentioned below.
> 
> I am dividing these changes according to section and screen sizes. so, that you will clear where to do changes
> 
> ## Header
> **Tablet**
> 
> * [x]  The logo is on the leftmost part. For now, I can't able to see the logo on the leftmost part.
> 
> ## HIghlights (top 3 articles)
> **All screen sizes**
> 
> * [x]  It contains 3 articles with an image as a background. For now, I am seeing you are not using the background image. Please change those images as a background.
> * [x]  The title of each article is a header (hx tag) and has a link (a tag). For now, I am seeing only the header tag and no link (a tag).
> 
> **Desktop**
> 
> * [x]  The TWN logo should appear over the first article, at the top left corner. For now, it's showing nothing
> * [x]  The date should appear over the first article, at the top right corner.
> 
> ## Latest Funding section
> **All screen sizes**
> 
> * [x]  The title of the section is a header (hx tag) and has a link (a tag). For now, I am seeing only the header tag and no link (a tag).
> * [x]  The nav menu (See more, Get updates, etc.) are grouped in a nav tag, and each one has link (a tag). For now, It is grouped in a `div` tag and did not use the anchor(a) tag.
> * [x]  Each article should have
>   - Its own title (hx tag) and has a link (a tag)
>   - Two categories items, with a link (a tag)
>   - A text excerpt at the bottom, that also has a link (a tag)
> * [x]  The gap between image and text is unresponsive. sometimes they overlap. Please fix that.
> 
> **Desktop**
> 
> * [x]  The nav menu should be on the left of the main title. For now, It is below the main title.
> * [x]  The first 4 articles appear in a row. For now, It's only 3.
> 
> ## Footer
> * [x]  Footer contains social media icons that should be grouped in the `nav` tag and each of them with a link (a tag).
> * [x]  Below the social media menu, there should be another menu also centered, with a `nav` tag. For now, it is wrapped in a div tag.
> 
> ## Reminder
> **"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have 2 code reviews left for this project."**
> 
> Code review by **Dipesh Kumar**
> 
> (Feel free to contact me on slack by the handle of **deep** if you have any additional question).
> Happy Coding
> [Dipesh Kumar](https://deeptwist.tk)
> [Twitter](https://twitter.com/97deepeshkumar)

Thank you for your review, we have implemented all the changes.

**Review by Zappat0n — APPROVED** [review]
# Status: Approved. 
Hello @prolajumokeoni and @emmyobonyo. 
You did an amazing job implementing all the changes required by Dipesh.


### Keep up the good work!.


[OPTIONAL] You could use the article tag for each article.


Feel free to reach me on slack @Zappat0n

**Comment by prolajumokeoni** [comment]
Thank you for your review @Zappat0n, we will use the article tag for each article.

**Pull request closed without merging**
